### ISSUE TITLE
Possibility of defining type of Yara rule sources.

### ISSUE THREAD

**Issue by pbalogh-sa** [openclarity/yara-rule-server#6]
## Problem Statement

It would be nice if we could define the type of the Yara rule sources.
```
rule_sources:
  - name: "base"
    url: "https://github.com/Yara-Rules/rules/archive/refs/heads/master.zip"
    exclude_regex: ".*index.*.yar|.*/utils/.*|.*/deprecated/.*|.*index_.*|.*MALW_AZORULT.yar"
   type: zip-archive
```
## Proposed Solution
There should be multiple types can be defined in the Yara rule server config:
```
type: git
type: tar-archive
type: directory
```
